### ISSUE TITLE
Client Crash 1.12.2 On placement

### ISSUE THREAD

**Issue by ghost** [AtomicBlom/WeirdingGadget#15]
Running newest release causes a client crash when the item is placed. 

```
[18:17:04] [Server thread/WARN] [FML]: Registry Block: Object did not get ID it asked for. Name: weirdinggadget:weirding_gadget Expected: 1893 Got: 2385
[18:17:04] [Server thread/WARN] [FML]: Registry Item: Object did not get ID it asked for. Name: weirdinggadget:weirding_gadget Expected: 7177 Got: 8999

[18:15:59] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `tile.weirdinggadget` for name `weirding_gadget`, expected `weirdinggadget`. This could be a intended override, but in most cases indicates a broken mod.

 

Description: Unexpected errorDescription: Unexpected error
java.lang.NullPointerException: Unexpected error at net.minecraftforge.common.ForgeChunkManager.requestPlayerTicket(ForgeChunkManager.java:714) at com.github.atomicblom.weirdinggadget.block.WeirdingGadgetBlock.activateChunkLoader(WeirdingGadgetBlock.java:92) at com.github.atomicblom.weirdinggadget.block.WeirdingGadgetBlock.func_180633_a(WeirdingGadgetBlock.java:87) at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186) at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:2965) at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467) at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96) at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578) at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253) at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019) at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807) at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Client threadStacktrace: at net.minecraftforge.common.ForgeChunkManager.requestPlayerTicket(ForgeChunkManager.java:714) at com.github.atomicblom.weirdinggadget.block.WeirdingGadgetBlock.activateChunkLoader(WeirdingGadgetBlock.java:92) at com.github.atomicblom.weirdinggadget.block.WeirdingGadgetBlock.func_180633_a(WeirdingGadgetBlock.java:87) at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186) at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:2965) at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467) at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96) at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578) at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253) at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)

 

Stacktrace:Stacktrace: at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532) at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by ghost** [comment]
Just tred the previous release and same issue. However, on reload the item is placed you just can't place another one. Oddly the item isn't removed from inventory when you place it.

**Comment by AtomicBlom** [comment]
What version of Forge?
Can I please get a list of any other mods you are using?

**Comment by ghost** [comment]
Forge Version: 1.12.2-forge1.12.2-14.23.5.2768

Here is FML log:
https://gist.github.com/cyris69/cb403e95bd13c33701a2075d01d07b66
Crash Report:
https://gist.github.com/cyris69/6e45ad4903bda7ed6958f9b34d8954f8
Mod List w/Versions: 
https://gist.github.com/cyris69/46457623db1d6a5e61285ba280f2b634

**Comment by MyWorldNetwork** [comment]
I can confirm exactly the same behaviour happens on my server.

Mod version: 2.0.13-universal

Forge version: 1.12.2 - 14.23.5.2836

Modlist here: http://www.myworldnetwork.net/rolecraft/

**Comment by AtomicBlom** [comment]
Hi @sentinel618 I don't suppose you have a crash log do you? I need to find something common between both of these reports because the original bug request makes no sense, unless somehow the world/player was nulled out by a coremod.

At this point I don't really have anything I can do but give you a build with ridiculous logs trying to get to the bottom of what I'm missing.

**Comment by MyWorldNetwork** [comment]
@AtomicBlom I do not but when I get home this evening (5 hours-ish) I can produce one

**Comment by AtomicBlom** [comment]
I've added additional logging to 2.1.15 on curseforge to help me figure out exactly what is null, if you could give that a spin and gist me the log, that would be awesome.

https://minecraft.curseforge.com/projects/the-weirding-gadget/files

**Comment by AtomicBlom** [comment]
I've added additional logging to 2.1.15 on curseforge to help me figure out exactly what is null, if you could give that a spin and gist me the log, that would be awesome.

https://minecraft.curseforge.com/projects/the-weirding-gadget/files

**Comment by AtomicBlom** [comment]
(pardon if this multiposts, I have no idea what's going on, my post isn't appearing for me)

I've added additional logging to 2.1.15 on curseforge to help me figure out exactly what is null, if you could give that a spin and gist me the log, that would be awesome.

https://minecraft.curseforge.com/projects/the-weirding-gadget/files

**Comment by MyWorldNetwork** [comment]
Same behaviour.

Mod version: 2.0.15-universal
Forge version: 1.12.2 - 14.23.5.2836

Server Log: https://pastebin.com/JytML10N
Client Crash Log: https://pastebin.com/4FTD88gi

Anything else, please let me know

**Comment by AtomicBlom** [comment]
I don't suppose you have the full server log do you? Unfortunately I'm not seeing any of the messages I was expecting to, E.g., one of these: https://github.com/AtomicBlom/WeirdingGadget/commit/f5fd8a320eb20537b82d804b38d199d06f280e12#diff-003c9c348317eb3471e99f7655691299R94

**Comment by MyWorldNetwork** [comment]
I don't think I'll have kept it but I can remove and replace tonight when I get home to generate a new logSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Steven Blom <notifications@github.com> Date: 13/05/2019  09:34  (GMT+00:00) To: AtomicBlom/WeirdingGadget <WeirdingGadget@noreply.github.com> Cc: sentinel618 <sentinel618@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [AtomicBlom/WeirdingGadget] Client Crash 1.12.2 On placement (#15) I don't suppose you have the full server log do you? Unfortunately I'm not seeing any of the messages I was expecting to, E.g., one of these: f5fd8a3#diff-003c9c348317eb3471e99f7655691299R94

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AtomicBlom/WeirdingGadget/issues/15#issuecomment-491728157",
"url": "https://github.com/AtomicBlom/WeirdingGadget/issues/15#issuecomment-491728157",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
