### ISSUE TITLE
Game crashed on TESR render when I died and respawned

### ISSUE THREAD

**Issue by Lothrazar** [AtomicBlom/WeirdingGadget#4]
I had one placed in the world near spawn, just testing in a creative world.  I used /kill command to respawned and game crashed with this log

`
[23:59:17] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:206) ~[bwx.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153) ~[bwx.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1008) ~[buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyBool{name=render_dynamic, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:223) ~[awu$a.class:?]
	at **com.github.atomicblom.weirdinggadget.client.rendering.WeirdingGadgetTESR.render(WeirdingGadgetTESR.java:27**) ~[WeirdingGadgetTESR.class:?]
	at com.github.atomicblom.weirdinggadget.client.rendering.WeirdingGadgetTESR.func_192841_a(WeirdingGadgetTESR.java:15) ~[WeirdingGadgetTESR.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197) ~[bwx.class:?]
	... 14 more
[23:59:18] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.4-120.jar)
  SoundFixPatchingLoader (AmbientSounds v2.2.0 mc1.12.2.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  FMLPlugin (elulib-0.1.11.jar)
Contact their authors BEFORE contacting forge`

**Comment by AtomicBlom** [comment]
Hmm, that's weird. You have a block of air that thinks it's a weirding gadget. I should probably guard against that.

**Comment by AtomicBlom** [comment]
Sorry for the delay, should be fixed in 1.12.2-2.0.4
