### ISSUE TITLE
Breaking changes in latest Forge 14.23.1.2576, open gl issue

### ISSUE THREAD

**Issue by Lothrazar** [AtomicBlom/WeirdingGadget#5]
In forge 2575 the mod loads fine, but in 2576 I get this error listed below

I think its because forge added breaking changes, when I look at changelog there is a bunch of rendering changes

http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2577/forge-1.12.2-14.23.1.2577-changelog.txt

	bartek.bok: Fix animation of rotated block parts (#4156)
	bartek.bok: Fix invalid rendering of single-frame B3D models (Fix #3815)
	bs2609: Adjust diffuse light calculation to match vanilla facing values (#4305)
	bs2609: Fix applyUVLock not preserving input order (#4336)
	bs2609: Adjust light matrix calculations to use per-face logic (#4339)

`java.lang.NullPointerException: Initializing game
	at com.github.atomicblom.weirdinggadget.client.opengex.OpenGEXState.apply(OpenGEXState.java:27)
	at net.minecraftforge.client.model.ModelStateComposition.apply(ModelStateComposition.java:43)
	at net.minecraftforge.client.model.MultiModelState.apply(MultiModelState.java:67)
	at net.minecraftforge.client.model.MultiModelState.getPartState(MultiModelState.java:50)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:718)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:186)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by NicosaurusRex99** [comment]
Same error here

**Comment by AtomicBlom** [comment]
I'm trying to get a replacement model to replace the OpenGex system, but with holidays there's been a few delays. I recommend downgrading Forge if you can in the short term.

**Comment by NicosaurusRex99** [comment]
I recommend this tool for any model creating https://mrcrayfish.com/tools?id=mc

**Comment by Darkosto** [comment]
I believe this is the same issue I just had: https://pastebin.com/imE4U50b

Wanted to throw this in just in case it helps out.
